# Generated by Django 6.0.4 on 2026-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bem', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('centro_custo', models.CharField(max_length=200)),
                ('descricao_cc', models.TextField()),
                ('responsavel', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('narrativa', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('imagem_1', models.ImageField(blank=True, null=True, upload_to='uploads/imagens/')),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to='uploads/imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
