# Generated by Django 6.0.4 on 2026-04-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bem',
            old_name='tag',
            new_name='descricao_tag',
        ),
    ]
