# Generated by Django 6.0.4 on 2026-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0002_rename_tag_bem_descricao_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bem',
            options={'ordering': ['numero_bem'], 'verbose_name': 'Bem', 'verbose_name_plural': 'Bens'},
        ),
        migrations.AddField(
            model_name='bem',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imagens/'),
        ),
        migrations.AddField(
            model_name='bem',
            name='imagem_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imagens/'),
        ),
        migrations.AddField(
            model_name='bem',
            name='imagem_5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imagens/'),
        ),
        migrations.AddField(
            model_name='bem',
            name='imagem_6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/imagens/'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='descricao_cc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='descricao_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='narrativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
