# Generated by Django 6.0.4 on 2026-05-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0003_alter_bem_options_bem_atualizado_em_bem_imagem_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bem',
            old_name='descricao_tag',
            new_name='descricao_bem',
        ),
    ]
